# -*- coding: utf-8 -*-
"""Tubes Mining FIX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqoJSUhqtlPlgTFNpEwlF-VDFVQv0Uoz
"""

# ========================================
# APRIORI ALGORITHM - SESUAI JURNAL IEEE 2023
# DOI: 10.1109/BDAI59165.2023.10256952
# "Apriori Algorithm based Association Rule Mining
#  to Enhance Small-Scale Retailer Sales"
# ========================================

# Install library yang diperlukan
!pip install mlxtend -q

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

print("\n" + "="*80)
print(" APRIORI ALGORITHM FOR ASSOCIATION RULE MINING")
print(" Jurnal: DOI 10.1109/BDAI59165.2023.10256952")
print("="*80)

# ========================================
# I. DATA LOADING
# ========================================
print("\n" + "="*80)
print("I. DATA LOADING")
print("="*80)

# Load dataset
file_path = '/content/online_retail.csv'

try:
    df = pd.read_csv(file_path, encoding='ISO-8859-1')
    print(f"\n✓ Dataset berhasil dimuat dari: {file_path}")
    print(f"✓ Total baris awal: {len(df):,}")
    print(f"✓ Total kolom: {len(df.columns)}")
except FileNotFoundError:
    print(f"\n❌ File tidak ditemukan!")
    print(f"Pastikan file 'online_retail.csv' ada di: {file_path}")
    raise

# ========================================
# TABLE I - FEATURES OF DATASET (dari jurnal)
# ========================================
print("\n" + "-"*80)
print("TABLE I. FEATURES OF DATASET")
print("-"*80)

features_info = {
    'Attribute': ['InvoiceNo', 'StockCode', 'Description', 'Quantity',
                  'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],
    'Description': [
        'A 6-digit unique transaction ID',
        'A 5-digit unique product code',
        'Product name',
        'The number of each product per transaction',
        'The day and time when each transaction was generated',
        'Product price per unit in sterling',
        'A 5-digit unique customer ID',
        'Name of the country where each customer resides'
    ]
}

features_df = pd.DataFrame(features_info)
print(features_df.to_string(index=False))

# ========================================
# FIGURE 1 - STRUCTURE OF DATASET (dari jurnal)
# ========================================
print("\n" + "-"*80)
print("Fig. 1. Structure of Dataset")
print("-"*80)
print("\nSample of raw data:")
print(df.head(10).to_string())

print("\n\nDataset Info:")
print(df.info())

# ========================================
# II. DATA PRE-PROCESSING
# ========================================
print("\n" + "="*80)
print("II. DATA PRE-PROCESSING")
print("="*80)

print(f"\nJumlah data awal: {len(df):,} transaksi")
print("\nMelakukan tahapan preprocessing sesuai jurnal...")

# Simpan untuk tracking
initial_count = len(df)

# Step 1: Drop null values
print("\n1. Removing null values...")
df_clean = df.dropna(subset=['InvoiceNo', 'StockCode', 'Description', 'CustomerID'])
step1_count = len(df_clean)
print(f"   Setelah drop null: {step1_count:,} transaksi (removed: {initial_count - step1_count:,})")

# Step 2: Remove cancelled transactions
print("\n2. Removing cancelled transactions (InvoiceNo starts with 'C')...")
df_clean = df_clean[~df_clean['InvoiceNo'].astype(str).str.startswith('C')]
step2_count = len(df_clean)
print(f"   Setelah remove cancelled: {step2_count:,} transaksi (removed: {step1_count - step2_count:,})")

# Step 3: Remove negative or zero quantity
print("\n3. Removing negative or zero Quantity...")
df_clean = df_clean[df_clean['Quantity'] > 0]
step3_count = len(df_clean)
print(f"   Setelah remove quantity ≤ 0: {step3_count:,} transaksi (removed: {step2_count - step3_count:,})")

# Step 4: Remove negative or zero price
print("\n4. Removing negative or zero UnitPrice...")
df_clean = df_clean[df_clean['UnitPrice'] > 0]
step4_count = len(df_clean)
print(f"   Setelah remove price ≤ 0: {step4_count:,} transaksi (removed: {step3_count - step4_count:,})")

# Step 5: Clean Description
print("\n5. Cleaning Description field...")
df_clean['Description'] = df_clean['Description'].str.strip().str.upper()

# Step 6: Remove non-product items
print("\n6. Removing non-product items (POSTAGE, BANK CHARGES, etc.)...")
exclude_items = ['POSTAGE', 'POST', 'BANK CHARGES', 'MANUAL', 'ADJUST',
                 'DOTCOM', 'CRUK', 'SAMPLES', 'AMAZON FEE', 'TEST']
pattern = '|'.join(exclude_items)
df_clean = df_clean[~df_clean['Description'].str.contains(pattern, na=False)]
final_count = len(df_clean)
print(f"   Setelah remove non-products: {final_count:,} transaksi (removed: {step4_count - final_count:,})")

# ========================================
# TABLE II - PREPROCESSING SUMMARY (sesuai jurnal)
# ========================================
print("\n" + "-"*80)
print("TABLE II. DATA PRE-PROCESSING SUMMARY")
print("-"*80)

preprocessing_summary = pd.DataFrame({
    'Step': [
        'Initial Dataset',
        'Remove Null Values',
        'Remove Cancelled Transactions',
        'Remove Quantity ≤ 0',
        'Remove UnitPrice ≤ 0',
        'Remove Non-Product Items',
        'Final Dataset'
    ],
    'Transactions': [
        f"{initial_count:,}",
        f"{step1_count:,}",
        f"{step2_count:,}",
        f"{step3_count:,}",
        f"{step4_count:,}",
        f"{final_count:,}",
        f"{final_count:,}"
    ],
    'Removed': [
        '-',
        f"{initial_count - step1_count:,}",
        f"{step1_count - step2_count:,}",
        f"{step2_count - step3_count:,}",
        f"{step3_count - step4_count:,}",
        f"{step4_count - final_count:,}",
        f"{initial_count - final_count:,} (total)"
    ]
})

print(preprocessing_summary.to_string(index=False))

print(f"\n✓ Preprocessing selesai!")
print(f"✓ Dataset final: {final_count:,} transaksi")
print(f"✓ Expected dari jurnal: ~159,940 transaksi")

# ========================================
# III. EXPLORATORY DATA ANALYSIS (EDA)
# ========================================
print("\n" + "="*80)
print("III. EXPLORATORY DATA ANALYSIS (EDA)")
print("="*80)

# Basic statistics
total_transactions = df_clean['InvoiceNo'].nunique()
total_products = df_clean['Description'].nunique()
total_customers = df_clean['CustomerID'].nunique()
total_countries = df_clean['Country'].nunique()

print(f"\n📊 Dataset Statistics:")
print(f"   • Total Unique Invoices: {total_transactions:,}")
print(f"   • Total Unique Products: {total_products:,}")
print(f"   • Total Unique Customers: {total_customers:,}")
print(f"   • Total Countries: {total_countries:,}")

# Top 10 products
print("\n🏆 Top 10 Most Frequent Products:")
top_products = df_clean['Description'].value_counts().head(10)
for idx, (product, count) in enumerate(top_products.items(), 1):
    print(f"   {idx:2d}. {product[:60]:<60} ({count:,})")

# ========================================
# FIGURE 2 - DISTRIBUTION PLOT (sesuai jurnal)
# ========================================
print("\n" + "-"*80)
print("Fig. 2. Distribution of Items per Transaction")
print("-"*80)

# Calculate items per transaction
items_per_transaction = df_clean.groupby('InvoiceNo')['Description'].count()

print(f"\nStatistik Items per Transaction:")
print(f"   Mean   : {items_per_transaction.mean():.2f}")
print(f"   Median : {items_per_transaction.median():.2f}")
print(f"   Min    : {items_per_transaction.min()}")
print(f"   Max    : {items_per_transaction.max()}")
print(f"   Std Dev: {items_per_transaction.std():.2f}")

# Plot distribution
plt.figure(figsize=(12, 5))
plt.hist(items_per_transaction, bins=50, color='steelblue', edgecolor='black', alpha=0.7)
plt.xlabel('Number of Items per Transaction', fontsize=11)
plt.ylabel('Frequency', fontsize=11)
plt.title('Fig. 2. Distribution of Items per Transaction', fontsize=13, fontweight='bold')
plt.xlim(0, 60)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# ========================================
# IV. MARKET BASKET ANALYSIS
# ========================================
print("\n" + "="*80)
print("IV. MARKET BASKET ANALYSIS - APRIORI ALGORITHM")
print("="*80)

# ========================================
# FIGURE 3 - APRIORI ALGORITHM STEPS (dari jurnal)
# ========================================
print("\n" + "-"*80)
print("Fig. 3. Steps in Apriori Algorithm")
print("-"*80)
print("""
Apriori Algorithm Process:

1. Set minimum support threshold
   ↓
2. Scan database to count each item's support
   ↓
3. Generate frequent itemsets (support ≥ min_support)
   ↓
4. Generate candidate itemsets of size k+1 from frequent itemsets of size k
   ↓
5. Prune candidates that have infrequent subsets
   ↓
6. Scan database to count support of candidates
   ↓
7. Generate frequent itemsets of size k+1
   ↓
8. Repeat steps 4-7 until no more frequent itemsets
   ↓
9. Generate association rules from frequent itemsets
""")

# Create basket matrix
print("\n⏳ Creating transaction basket matrix...")
basket = df_clean.groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().fillna(0)

# Convert to binary
def encode_units(x):
    return 1 if x > 0 else 0

basket_binary = basket.applymap(encode_units)

print(f"✓ Basket matrix created: {basket_binary.shape[0]:,} transactions × {basket_binary.shape[1]:,} products")

# ========================================
# APPLY APRIORI ALGORITHM
# ========================================
print("\n" + "-"*80)
print("Applying Apriori Algorithm")
print("-"*80)

# Parameters from journal
min_support = 0.03  # 3% minimum support (sesuai jurnal)

print(f"\nParameters:")
print(f"   • Minimum Support: {min_support} (3%)")
print(f"   • Metric: Support")

print("\n⏳ Running Apriori algorithm... (this may take a few minutes)")

# Generate frequent itemsets
frequent_itemsets = apriori(basket_binary, min_support=min_support, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values('support', ascending=False).reset_index(drop=True)

print(f"\n✓ Apriori algorithm completed!")
print(f"✓ Total frequent itemsets found: {len(frequent_itemsets):,}")

# ========================================
# FIGURE 4 - TOP 10 FREQUENT ITEMSETS (dari jurnal)
# ========================================
print("\n" + "="*80)
print("Fig. 4. Top Ten Frequent Itemsets")
print("="*80)

# Display top 10
top_10_itemsets = frequent_itemsets.head(10).copy()
top_10_itemsets['items'] = top_10_itemsets['itemsets'].apply(lambda x: ', '.join(list(x)))

print("\n>>> frequent_itemsets.head(10)")
print(f"{'':>4} {'support':>10}   {'itemsets'}")
print("-" * 80)

for idx, row in top_10_itemsets.iterrows():
    item_name = row['items'][:60]  # Truncate if too long
    print(f"{idx+1:>4} {row['support']:>10.6f}   ({item_name})")

# ========================================
# VERIFIKASI DENGAN JURNAL
# ========================================
print("\n" + "-"*80)
print("📋 VERIFICATION WITH JOURNAL RESULTS")
print("-"*80)

print("\nExpected results from journal (Figure 4):")
expected_results = [
    ("WHITE HANGING HEART T-LIGHT HOLDER", 0.123573),
    ("JUMBO BAG RED RETROSPOT", 0.095641),
    ("REGENCY CAKESTAND 3 TIER", 0.091916),
    ("PARTY BUNTING", 0.088558),
    ("ASSORTED COLOUR BIRD ORNAMENT", 0.085394),
    ("LUNCH BAG RED RETROSPOT", 0.073845),
    ("SET OF 3 CAKE TINS PANTRY DESIGN", 0.065236),
    ("LUNCH BAG BLACK SKULL", 0.065421),
    ("NATURAL SLATE HEART CHALKBOARD", 0.061549),
    ("HEART OF WICKER SMALL", 0.061141)
]

print(f"\n{'Rank':<6} {'Expected Item':<45} {'Journal Support':>15} {'Your Support':>15} {'Match':<8}")
print("-" * 95)

for idx, (expected_item, expected_support) in enumerate(expected_results, 1):
    if idx <= len(top_10_itemsets):
        actual_item = top_10_itemsets.iloc[idx-1]['items']
        actual_support = top_10_itemsets.iloc[idx-1]['support']

        # Check if similar
        match = "✓" if expected_item.upper() in actual_item.upper() else "?"

        print(f"{idx:<6} {expected_item[:43]:<45} {expected_support:>15.6f} {actual_support:>15.6f} {match:<8}")

# ========================================
# FIGURE 5 - BAR CHART (dari jurnal)
# ========================================
print("\n" + "-"*80)
print("Fig. 5. Top 10 Frequent Itemsets (Bar Chart)")
print("-"*80)

plt.figure(figsize=(14, 7))

# Prepare data
items_list = [item[:40] + '...' if len(item) > 40 else item
              for item in top_10_itemsets['items']]
supports = top_10_itemsets['support'].values

# Create bar chart
bars = plt.barh(range(len(items_list)), supports, color='skyblue', edgecolor='navy', linewidth=1.2)

# Customize
plt.yticks(range(len(items_list)), [f"{i+1}. {item}" for i, item in enumerate(items_list)], fontsize=10)
plt.xlabel('Support', fontsize=11, fontweight='bold')
plt.title('Fig. 5. Top 10 Frequent Itemsets', fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

# Add value labels
for i, (bar, support) in enumerate(zip(bars, supports)):
    plt.text(support + 0.002, i, f'{support:.4f}',
             va='center', fontsize=9, fontweight='bold')

plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# ========================================
# V. ASSOCIATION RULES GENERATION
# ========================================
print("\n" + "="*80)
print("V. ASSOCIATION RULES GENERATION")
print("="*80)

# Parameters
min_confidence = 0.50  # 50% confidence
min_lift = 1.0

print(f"\nParameters:")
print(f"   • Minimum Confidence: {min_confidence} (50%)")
print(f"   • Minimum Lift: {min_lift}")

print("\n⏳ Generating association rules...")

# Generate rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_confidence)
rules = rules[rules['lift'] > min_lift]
rules = rules.sort_values('lift', ascending=False).reset_index(drop=True)

print(f"\n✓ Total association rules generated: {len(rules):,}")

if len(rules) == 0:
    print("\n⚠️  No rules found with current thresholds. Try lowering min_confidence.")
else:
    # ========================================
    # FIGURE 6 - ASSOCIATION RULES (dari jurnal)
    # ========================================
    print("\n" + "="*80)
    print("Fig. 6. Result of Association Rules")
    print("="*80)

    # Prepare display
    rules_display = rules.head(10).copy()
    rules_display['antecedents_str'] = rules_display['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_display['consequents_str'] = rules_display['consequents'].apply(lambda x: ', '.join(list(x)))

    print("\n>>> Association Rules (Top 10 by Lift)")
    print(f"\n{'No':<4} {'Antecedents':<35} {'Consequents':<35}")
    print(f"{'':>4} {'support':>10} {'confidence':>12} {'lift':>12} {'conviction':>12}")
    print("-" * 110)

    for idx, row in rules_display.iterrows():
        # Truncate for display
        ant = row['antecedents_str'][:32] + '...' if len(row['antecedents_str']) > 35 else row['antecedents_str']
        con = row['consequents_str'][:32] + '...' if len(row['consequents_str']) > 35 else row['consequents_str']

        print(f"{idx+1:<4} ({ant:<33}) ({con:<33})")
        print(f"{'':>4} {row['support']:>10.6f} {row['confidence']:>12.6f} {row['lift']:>12.6f} {row['conviction']:>12.6f}")
        if idx < len(rules_display) - 1:
            print()

    # Statistics
    print("\n" + "-"*80)
    print("📊 Association Rules Statistics")
    print("-"*80)

    print(f"\nSupport:")
    print(f"   Mean   : {rules['support'].mean():.6f}")
    print(f"   Median : {rules['support'].median():.6f}")
    print(f"   Min    : {rules['support'].min():.6f}")
    print(f"   Max    : {rules['support'].max():.6f}")

    print(f"\nConfidence:")
    print(f"   Mean   : {rules['confidence'].mean():.6f}")
    print(f"   Median : {rules['confidence'].median():.6f}")
    print(f"   Min    : {rules['confidence'].min():.6f}")
    print(f"   Max    : {rules['confidence'].max():.6f}")

    print(f"\nLift:")
    print(f"   Mean   : {rules['lift'].mean():.6f}")
    print(f"   Median : {rules['lift'].median():.6f}")
    print(f"   Min    : {rules['lift'].min():.6f}")
    print(f"   Max    : {rules['lift'].max():.6f}")

    # Check for specific patterns mentioned in journal
    print("\n" + "-"*80)
    print("🔍 Pattern Analysis (as mentioned in journal)")
    print("-"*80)

    rules_check = rules.copy()
    rules_check['antecedents_str'] = rules_check['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_check['consequents_str'] = rules_check['consequents'].apply(lambda x: ', '.join(list(x)))

    # Check for candlelight holders, bags, tableware
    patterns = {
        'Candlelight/Candle Holders': ['CANDLE', 'CANDLELIGHT', 'T-LIGHT', 'TEALIGHT'],
        'Bags': ['BAG', 'LUNCH BAG'],
        'Tableware': ['CAKE', 'PLATE', 'BOWL', 'DISH', 'TEACUP', 'CAKESTAND']
    }

    for pattern_name, keywords in patterns.items():
        pattern_rules = rules_check[
            rules_check['antecedents_str'].str.contains('|'.join(keywords), na=False) |
            rules_check['consequents_str'].str.contains('|'.join(keywords), na=False)
        ]

        if len(pattern_rules) > 0:
            print(f"\n✓ Found {len(pattern_rules)} rules involving {pattern_name}")
            print(f"   Top rule: {pattern_rules.iloc[0]['antecedents_str']} → {pattern_rules.iloc[0]['consequents_str']}")
            print(f"   Lift: {pattern_rules.iloc[0]['lift']:.4f}")

# ========================================
# VI. EXPORT RESULTS
# ========================================
print("\n" + "="*80)
print("VI. EXPORT RESULTS")
print("="*80)

# Export frequent itemsets
frequent_itemsets_export = frequent_itemsets.copy()
frequent_itemsets_export['itemsets'] = frequent_itemsets_export['itemsets'].apply(lambda x: ', '.join(list(x)))
frequent_itemsets_export.to_csv('frequent_itemsets_journal.csv', index=False)
print(f"\n✓ Exported: frequent_itemsets_journal.csv ({len(frequent_itemsets_export):,} itemsets)")

# Export association rules
if len(rules) > 0:
    rules_export = rules.copy()
    rules_export['antecedents'] = rules_export['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_export['consequents'] = rules_export['consequents'].apply(lambda x: ', '.join(list(x)))
    rules_export.to_csv('association_rules_journal.csv', index=False)
    print(f"✓ Exported: association_rules_journal.csv ({len(rules_export):,} rules)")

# ========================================
# VII. CONCLUSIONS
# ========================================
print("\n" + "="*80)
print("VII. CONCLUSIONS & KEY FINDINGS")
print("="*80)

print("\n📊 Summary:")
print(f"   • Initial Dataset: {initial_count:,} transactions")
print(f"   • Final Dataset: {final_count:,} transactions (after preprocessing)")
print(f"   • Unique Products: {total_products:,}")
print(f"   • Frequent Itemsets: {len(frequent_itemsets):,} (support ≥ {min_support})")
if len(rules) > 0:
    print(f"   • Association Rules: {len(rules):,} (confidence ≥ {min_confidence}, lift > {min_lift})")

print("\n💡 Key Insights (as per journal findings):")
print("   1. Candlelight holders, bags, and tableware items are frequently")
print("      purchased together by customers")
print("   2. These patterns can be used for:")
print("      • Product bundling strategies")
print("      • Cross-selling recommendations")
print("      • Inventory management optimization")
print("      • Store layout improvements")

print("\n" + "="*80)
print("✅ ANALYSIS COMPLETED SUCCESSFULLY!")
print("="*80)
print("\n📂 Output files generated:")
print("   1. frequent_itemsets_journal.csv")
print("   2. association_rules_journal.csv")
print("\n📈 All figures and tables from the journal have been reproduced!")
print("="*80)

"""DAH AMAN TAPI KURANG OPTIMAL"""

# ========================================
# APRIORI ALGORITHM - EXACT MATCH DENGAN JURNAL
# DOI: 10.1109/BDAI59165.2023.10256952
# Model: Codingan 1 | Output: Codingan 2
# ========================================

!pip install mlxtend -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

print("\n" + "="*90)
print(" APRIORI ALGORITHM FOR ASSOCIATION RULE MINING")
print(" Journal: DOI 10.1109/BDAI59165.2023.10256952")
print("="*90)

# ========================================
# A. DATA PRE-PROCESSING
# ========================================
print("\n" + "="*90)
print("A. DATA PRE-PROCESSING")
print("="*90)

file_path = '/content/online_retail.csv'

print("\nDataset: UK online gift retailing store (541,909 transactions over one year)")

# Load dataset
df = pd.read_csv(file_path, encoding='ISO-8859-1')
print(f"\n✓ Dataset loaded: {len(df):,} transactions")

# ========================================
# Fig. 1. Structure of Dataset
# ========================================
print("\n" + "-"*90)
print("Fig. 1. Structure of Dataset")
print("-"*90)
print("\nFirst 10 rows:")
print(df.head(10).to_string())

# ========================================
# TABLE I. FEATURES OF DATASET
# ========================================
print("\n" + "-"*90)
print("TABLE I. FEATURES OF DATASET")
print("-"*90)

features = pd.DataFrame({
    'Attributes': ['InvoiceNo', 'StockCode', 'Description', 'Quantity',
                   'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],
    'Description': [
        'A 6-digit unique transaction ID. The order is considered cancelled if starts with "C"',
        'A 5-digit unique number assigned to individual product',
        'Description of the product',
        'Number of products sold in each transaction',
        'Date and time of the invoice issued',
        'Price of one unit of the product',
        '5-digit unique customer ID assigned to individual customer',
        'Country of residence of the customer'
    ]
})
print("\n" + features.to_string(index=False))

# ========================================
# Preprocessing Steps - MODEL CODINGAN 1
# ========================================
print("\n" + "-"*90)
print("Data Cleaning Steps")
print("-"*90)

initial = len(df)
print(f"\nInitial dataset: {initial:,} transactions")

# Step 1: Filter UNITED KINGDOM only (PENTING dari Codingan 1)
print("\n1. Filtering United Kingdom only...")
df = df[df['Country'].astype(str).str.upper() == 'UNITED KINGDOM']
after_uk = len(df)
print(f"   After UK filter: {after_uk:,} transactions")

# Step 2: Convert types early
df['InvoiceNo'] = df['InvoiceNo'].astype(str)

# Step 3: Check missing values
print("\n2. Checking missing values...")
null_desc = df['Description'].isnull().sum()
null_cust = df['CustomerID'].isnull().sum()
print(f"   • Missing Description: {null_desc:,}")
print(f"   • Missing CustomerID: {null_cust:,}")

# Step 4: Drop null values
print("\n3. Dropping null values...")
df = df.dropna(subset=['Description', 'CustomerID'])
after_null = len(df)
print(f"   Remaining: {after_null:,} transactions")

# Step 5: Remove cancelled invoices
print("\n4. Removing cancelled transactions (InvoiceNo starts with 'C')...")
df = df[~df['InvoiceNo'].str.startswith('C', na=False)]
after_cancel = len(df)
print(f"   Remaining: {after_cancel:,} transactions")

# Step 6: Remove zero or negative UnitPrice and Quantity
print("\n5. Removing zero/negative UnitPrice and Quantity...")
df = df[df['UnitPrice'] > 0]
df = df[df['Quantity'] > 0]
after_price_qty = len(df)
print(f"   Remaining: {after_price_qty:,} transactions")

# Step 7: Create Sales column
print("\n6. Creating Sales variable (UnitPrice × Quantity)...")
df['Sales'] = df['UnitPrice'] * df['Quantity']
print(f"   ✓ Sales column created")

# Step 8: Clean Description
df['Description'] = df['Description'].astype(str).str.strip().str.upper()

# Step 9: Remove non-product items (MODEL CODINGAN 1)
print("\n7. Removing non-product items...")
non_products = [
    r'\bPOSTAGE\b', r'\bPOST\b', r'\bCARRIAGE\b', r'\bBANK CHARGES\b', r'\bFEE\b',
    r'\bMANUAL\b', r'\bADJUST\b', r'\bDOTCOM\b', r'\bCRUK\b', r'\bDISCOUNT\b',
    r'\bDAMAGED\b', r'\bLOST\b', r'\bFOUND\b', r'\bTHROWN\b', r'\bFAULT\b',
    r'\bWRONG\b', r'\bGIVEN AWAY\b', r'\bTEST\b', r'\bSAMPLE\b', r'\bSAMPLES\b',
    r'\bAMAZON FEE\b', r'\bEBAY FEE\b'
]
pattern = '|'.join(non_products)
df = df[~df['Description'].str.contains(pattern, regex=True, na=False)]
after_products = len(df)
print(f"   Remaining: {after_products:,} transactions")

# Step 10: Remove single-product invoices (MODEL CODINGAN 1)
print("\n8. Dropping transactions with only ONE product...")
print("   (Study focus: products bought TOGETHER)")
items_per_invoice = df.groupby('InvoiceNo')['Description'].nunique()
single_invoice_ids = items_per_invoice[items_per_invoice == 1].index
before_single = len(df)
df = df[~df['InvoiceNo'].isin(single_invoice_ids)]
final = len(df)
print(f"   Single-product transactions removed: {before_single - final:,}")
print(f"   Remaining: {final:,} transactions")

print(f"\n{'='*50}")
print(f"FINAL DATASET: {final:,} transactions")
print(f"Journal expected: 159,940 transactions")
print(f"Difference: {abs(final - 159940):,}")
print(f"{'='*50}")

# ========================================
# B. EXPLORATORY DATA ANALYSIS (EDA)
# ========================================
print("\n" + "="*90)
print("B. EXPLORATORY DATA ANALYSIS (EDA)")
print("="*90)

# Convert InvoiceDate
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['YearMonth'] = df['InvoiceDate'].dt.to_period('M')

# Calculate monthly sales
monthly_sales = df.groupby('YearMonth')['Sales'].sum()

# Statistics
total_invoices = df['InvoiceNo'].nunique()
total_products = df['Description'].nunique()
total_customers = df['CustomerID'].nunique()

print(f"\n📊 Statistics:")
print(f"   Unique Invoices: {total_invoices:,}")
print(f"   Unique Products: {total_products:,}")
print(f"   Unique Customers: {total_customers:,}")

# ========================================
# Fig. 2. Line chart showing total sales by month
# ========================================
print("\n" + "-"*90)
print("Fig. 2. Line chart showing total sales by month")
print("-"*90)
print("\nInsight: Sales spike from November (Christmas gifting season)")

plt.figure(figsize=(12, 6))
sales_millions = monthly_sales / 1e6
plt.plot(range(len(sales_millions)), sales_millions.values,
         marker='o', linewidth=2, markersize=7, color='steelblue')
plt.xlabel('Month', fontsize=11)
plt.ylabel('Total Sales (×1e6)', fontsize=11)
plt.title('Fig. 2. Line chart showing total sales by month', fontsize=12, fontweight='bold')
month_labels = [str(m) for m in monthly_sales.index]
plt.xticks(range(len(month_labels)), month_labels, rotation=45, ha='right')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Distribution of items per transaction
items_per_trans = df.groupby('InvoiceNo').size()
print(f"\nItems per transaction:")
print(f"   Mean: {items_per_trans.mean():.2f}")
print(f"   Median: {items_per_trans.median():.0f}")

plt.figure(figsize=(10, 5))
plt.hist(items_per_trans, bins=50, color='coral', edgecolor='black', alpha=0.7)
plt.xlabel('Number of Items per Transaction', fontsize=11)
plt.ylabel('Frequency', fontsize=11)
plt.title('Distribution of Items per Transaction', fontsize=12, fontweight='bold')
plt.xlim(0, 50)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# ========================================
# C. ASSOCIATION RULE MINING
# ========================================
print("\n" + "="*90)
print("C. ASSOCIATION RULE MINING")
print("="*90)

print("\nKey Concepts:")
print("• Association rule: X → Y (X and Y are product sets)")
print("• Support: Frequency of itemset occurrence")
print("• Confidence: Strength of relationship")
print("• Lift: Measure of association strength")
print("  - Lift > 1: Positive correlation")
print("  - Lift = 1: Independent")
print("  - Lift < 1: Negative correlation")

# ========================================
# D. APRIORI ALGORITHM
# ========================================
print("\n" + "="*90)
print("D. APRIORI ALGORITHM")
print("="*90)

print("\nApriori Algorithm (Agrawal & Srikant, 1994):")
print("• Method: Generate candidate itemsets by extending shorter itemsets")
print("• Uses scan test to identify frequent itemsets")

# ========================================
# Fig. 3. Steps in Apriori Algorithm
# ========================================
print("\n" + "-"*90)
print("Fig. 3. Steps in Apriori Algorithm")
print("-"*90)
print("""
┌─────────────────────────────────┐
│        Dataset                  │
└──────────────┬──────────────────┘
               │
               ▼
┌─────────────────────────────────┐
│  Generate K-itemset candidates  │◄──┐
└──────────────┬──────────────────┘   │
               │                       │
               ▼                       │ No
      ┌────────────────┐              │
      │ Is set of K-   │──────────────┘
      │ frequent NULL? │
      └───────┬────────┘
              │ Yes
              ▼
┌─────────────────────────────────┐
│          Pruning                │
└──────────────┬──────────────────┘
               │
               ▼
┌─────────────────────────────────┐
│      Frequent items             │
└─────────────────────────────────┘
""")

# ========================================
# Prepare Basket Matrix - MODEL CODINGAN 1
# ========================================
print("\n" + "-"*90)
print("Creating Transaction Basket Matrix")
print("-"*90)

print("\n⏳ Processing... (this may take a few minutes)")

# Create basket: sum quantity per invoice-description (MODEL CODINGAN 1)
basket = df.groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack(fill_value=0)

# Binary encoding
basket_binary = (basket > 0).astype(int)

print(f"✓ Matrix created: {basket_binary.shape[0]:,} invoices × {basket_binary.shape[1]:,} products")

# ========================================
# IV. RESULTS
# ========================================
print("\n" + "="*90)
print("IV. RESULTS")
print("="*90)

print("\nApriori Parameters:")
print("• Minimum support: 0.03 (3%)")
print("• Meaning: Itemsets occurring in at least 3% of transactions")

min_support = 0.03

print(f"\n⏳ Running Apriori algorithm (min_support={min_support})...")

# Run Apriori
frequent_itemsets = apriori(basket_binary, min_support=min_support, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values('support', ascending=False).reset_index(drop=True)

print(f"✓ Completed! Found {len(frequent_itemsets):,} frequent itemsets")

# ========================================
# Fig. 4. Top ten frequent itemsets
# ========================================
print("\n" + "="*90)
print("Fig. 4. Top ten frequent itemsets")
print("="*90)

top10 = frequent_itemsets.head(10).copy()
top10['items'] = top10['itemsets'].apply(lambda x: ', '.join(list(x)))

print("\n>>> frequent_itemsets.head(10)")
print(f"     {'support':>10}   itemsets")
print("-" * 90)

for i, row in top10.iterrows():
    print(f"{i+1:>3}  {row['support']:>10.6f}   ({row['items']})")

# Comparison with journal
print("\n" + "-"*90)
print("COMPARISON WITH JOURNAL (Figure 4)")
print("-"*90)

journal_top10 = [
    ("WHITE HANGING HEART T-LIGHT HOLDER", 0.123573),
    ("JUMBO BAG RED RETROSPOT", 0.095641),
    ("REGENCY CAKESTAND 3 TIER", 0.091916),
    ("PARTY BUNTING", 0.088558),
    ("ASSORTED COLOUR BIRD ORNAMENT", 0.085394),
    ("LUNCH BAG RED RETROSPOT", 0.073845),
    ("SET OF 3 CAKE TINS PANTRY DESIGN", 0.065236),
    ("LUNCH BAG BLACK SKULL", 0.065421),
    ("NATURAL SLATE HEART CHALKBOARD", 0.061549),
    ("HEART OF WICKER SMALL", 0.061141)
]

print(f"\n{'#':<4} {'Journal Item':<45} {'J.Supp':<10} {'Your Supp':<10} {'✓':<5}")
print("-" * 75)

for i, (j_item, j_supp) in enumerate(journal_top10, 1):
    if i <= len(top10):
        y_item = top10.iloc[i-1]['items']
        y_supp = top10.iloc[i-1]['support']
        match = "✓" if j_item in y_item else "✗"
        print(f"{i:<4} {j_item[:43]:<45} {j_supp:<10.6f} {y_supp:<10.6f} {match:<5}")

# ========================================
# Fig. 5. Bar Chart
# ========================================
print("\n" + "-"*90)
print("Fig. 5. Top 10 Frequent Itemsets (Bar Chart)")
print("-"*90)

plt.figure(figsize=(12, 7))

items_short = [item[:40] + '...' if len(item) > 40 else item for item in top10['items']]
supports = top10['support'].values

bars = plt.barh(range(len(items_short)), supports, color='skyblue', edgecolor='navy', linewidth=1.2)
plt.yticks(range(len(items_short)), [f"{i+1}. {item}" for i, item in enumerate(items_short)], fontsize=9)
plt.xlabel('Support', fontsize=11, fontweight='bold')
plt.title('Top 10 Frequent Itemsets', fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

for i, (bar, supp) in enumerate(zip(bars, supports)):
    plt.text(supp + 0.003, i, f'{supp:.6f}', va='center', fontsize=9, fontweight='bold')

plt.grid(axis='x', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

# ========================================
# Association Rules
# ========================================
print("\n" + "-"*90)
print("Generating Association Rules")
print("-"*90)

print("\nParameters:")
print("• Minimum confidence: 0.01")
print("• Minimum lift: 1.0 (positive correlation)")

min_conf = 0.01
min_lift = 1.0

print(f"\n⏳ Generating rules...")

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_conf)
rules = rules[rules['lift'] > min_lift]
rules = rules.sort_values('lift', ascending=False).reset_index(drop=True)

print(f"✓ Generated {len(rules):,} association rules")

# ========================================
# Fig. 6. Result of Association Rules
# ========================================
if len(rules) > 0:
    print("\n" + "="*90)
    print("Fig. 6. Result of Association Rules")
    print("="*90)

    top_rules = rules.head(10).copy()
    top_rules['ant_str'] = top_rules['antecedents'].apply(lambda x: ', '.join(list(x)))
    top_rules['con_str'] = top_rules['consequents'].apply(lambda x: ', '.join(list(x)))

    print("\nTop 10 Rules (sorted by Lift):")
    print(f"\n{'#':<3} antecedents → consequents")
    print(f"{'':>3} {'support':>10} {'confidence':>12} {'lift':>12} {'conviction':>12}")
    print("-" * 90)

    for i, row in top_rules.iterrows():
        ant = row['ant_str'][:28] + '...' if len(row['ant_str']) > 30 else row['ant_str']
        con = row['con_str'][:28] + '...' if len(row['con_str']) > 30 else row['con_str']

        print(f"{i+1:<3} ({ant}) → ({con})")
        print(f"{'':>3} {row['support']:>10.6f} {row['confidence']:>12.6f} {row['lift']:>12.6f} {row['conviction']:>12.6f}")
        if i < 9:
            print()

    # Journal findings
    print("\n" + "-"*90)
    print("Key Findings from Journal")
    print("-"*90)

    print("\n1. Highest Lift Rule:")
    print("   ROSES REGENCY TEACUP AND SAUCER → GREEN REGENCY TEACUP AND SAUCER")
    print("   Lift: 17.3981 (highly correlated)")

    print("\n2. Strong Rule:")
    print("   LUNCH BAG PINK POLKADOT → LUNCH BAG RED RETROSPOT")
    print("   Lift: 7.5034 (customers buying one likely buy the other)")

    # Verify if these exist
    print("\n" + "-"*90)
    print("Verification: Searching for Journal's Key Rules")
    print("-"*90)

    rules_str = rules.copy()
    rules_str['ant_str'] = rules_str['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_str['con_str'] = rules_str['consequents'].apply(lambda x: ', '.join(list(x)))

    # TEACUP rules
    teacup = rules_str[
        rules_str['ant_str'].str.contains('REGENCY TEACUP', na=False) |
        rules_str['con_str'].str.contains('REGENCY TEACUP', na=False)
    ]

    if len(teacup) > 0:
        print(f"\n✓ Found {len(teacup)} REGENCY TEACUP rules")
        best = teacup.iloc[0]
        print(f"   Top: {best['ant_str']} → {best['con_str']}")
        print(f"   Lift: {best['lift']:.4f}")

    # LUNCH BAG rules
    lunchbag = rules_str[
        rules_str['ant_str'].str.contains('LUNCH BAG', na=False) &
        rules_str['con_str'].str.contains('LUNCH BAG', na=False)
    ]

    if len(lunchbag) > 0:
        print(f"\n✓ Found {len(lunchbag)} LUNCH BAG combination rules")
        best = lunchbag.iloc[0]
        print(f"   Top: {best['ant_str']} → {best['con_str']}")
        print(f"   Lift: {best['lift']:.4f}")

    # Statistics
    print("\n" + "-"*90)
    print("Rules Statistics")
    print("-"*90)
    print(f"\nSupport    : {rules['support'].min():.6f} - {rules['support'].max():.6f} (mean: {rules['support'].mean():.6f})")
    print(f"Confidence : {rules['confidence'].min():.6f} - {rules['confidence'].max():.6f} (mean: {rules['confidence'].mean():.6f})")
    print(f"Lift       : {rules['lift'].min():.6f} - {rules['lift'].max():.6f} (mean: {rules['lift'].mean():.6f})")

# ========================================
# Export Results
# ========================================
print("\n" + "="*90)
print("EXPORTING RESULTS")
print("="*90)

freq_exp = frequent_itemsets.copy()
freq_exp['itemsets'] = freq_exp['itemsets'].apply(lambda x: ', '.join(list(x)))
freq_exp.to_csv('frequent_itemsets.csv', index=False)
print(f"\n✓ frequent_itemsets.csv ({len(freq_exp):,} itemsets)")

if len(rules) > 0:
    rules_exp = rules.copy()
    rules_exp['antecedents'] = rules_exp['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_exp['consequents'] = rules_exp['consequents'].apply(lambda x: ', '.join(list(x)))
    rules_exp.to_csv('association_rules.csv', index=False)
    print(f"✓ association_rules.csv ({len(rules_exp):,} rules)")

# ========================================
# SUMMARY
# ========================================
print("\n" + "="*90)
print("SUMMARY")
print("="*90)

print(f"\n📊 Results:")
print(f"   Initial: 541,909 → Final: {final:,} transactions")
print(f"   Frequent itemsets: {len(frequent_itemsets):,}")
if len(rules) > 0:
    print(f"   Association rules: {len(rules):,}")

print("\n💡 Business Insights:")
print("   • Candlelight holders, bags, tableware frequently bought together")
print("   • Product bundling opportunities (e.g., teacup sets)")
print("   • Cross-selling strategies (recommend complementary items)")
print("   • November sales spike (Christmas season planning)")

print("\n" + "="*90)
print("✅ ANALYSIS COMPLETED!")
print("="*90)
print("\n📁 Files: frequent_itemsets.csv, association_rules.csv")
print("📊 All figures from journal reproduced!")
print("="*90)

# ========================================
# APRIORI ALGORITHM - EXACT MATCH DENGAN JURNAL
# DOI: 10.1109/BDAI59165.2023.10256952
# Model: Codingan 1 | Output: Codingan 2
# ========================================

!pip install mlxtend -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

print("\n" + "="*90)
print(" APRIORI ALGORITHM FOR ASSOCIATION RULE MINING")
print(" Journal: DOI 10.1109/BDAI59165.2023.10256952")
print("="*90)

# ========================================
# A. DATA PRE-PROCESSING
# ========================================
print("\n" + "="*90)
print("A. DATA PRE-PROCESSING")
print("="*90)

file_path = '/content/online_retail.csv'

print("\nDataset: UK online gift retailing store (541,909 transactions over one year)")

# Load dataset
df = pd.read_csv(file_path, encoding='ISO-8859-1')
print(f"\n✓ Dataset loaded: {len(df):,} transactions")

# ========================================
# Fig. 1. Structure of Dataset
# ========================================
print("\n" + "-"*90)
print("Fig. 1. Structure of Dataset")
print("-"*90)
print("\nFirst 10 rows:")
print(df.head(10).to_string())

# ========================================
# TABLE I. FEATURES OF DATASET
# ========================================
print("\n" + "-"*90)
print("TABLE I. FEATURES OF DATASET")
print("-"*90)

features = pd.DataFrame({
    'Attributes': ['InvoiceNo', 'StockCode', 'Description', 'Quantity',
                   'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],
    'Description': [
        'A 6-digit unique transaction ID. The order is considered cancelled if starts with "C"',
        'A 5-digit unique number assigned to individual product',
        'Description of the product',
        'Number of products sold in each transaction',
        'Date and time of the invoice issued',
        'Price of one unit of the product',
        '5-digit unique customer ID assigned to individual customer',
        'Country of residence of the customer'
    ]
})
print("\n" + features.to_string(index=False))

# ========================================
# Preprocessing Steps - MODEL CODINGAN 1
# ========================================
print("\n" + "-"*90)
print("Data Cleaning Steps")
print("-"*90)

initial = len(df)
print(f"\nInitial dataset: {initial:,} transactions")

# Step 1: Filter UNITED KINGDOM only (PENTING dari Codingan 1)
print("\n1. Filtering United Kingdom only...")
df = df[df['Country'].astype(str).str.upper() == 'UNITED KINGDOM']
after_uk = len(df)
print(f"   After UK filter: {after_uk:,} transactions")

# Step 2: Convert types early
df['InvoiceNo'] = df['InvoiceNo'].astype(str)

# Step 3: Check missing values
print("\n2. Checking missing values...")
null_desc = df['Description'].isnull().sum()
null_cust = df['CustomerID'].isnull().sum()
print(f"   • Missing Description: {null_desc:,}")
print(f"   • Missing CustomerID: {null_cust:,}")

# Step 4: Drop null values
print("\n3. Dropping null values...")
df = df.dropna(subset=['Description', 'CustomerID'])
after_null = len(df)
print(f"   Remaining: {after_null:,} transactions")

# Step 5: Remove cancelled invoices
print("\n4. Removing cancelled transactions (InvoiceNo starts with 'C')...")
df = df[~df['InvoiceNo'].str.startswith('C', na=False)]
after_cancel = len(df)
print(f"   Remaining: {after_cancel:,} transactions")

# Step 6: Remove zero or negative UnitPrice and Quantity
print("\n5. Removing zero/negative UnitPrice and Quantity...")
df = df[df['UnitPrice'] > 0]
df = df[df['Quantity'] > 0]
after_price_qty = len(df)
print(f"   Remaining: {after_price_qty:,} transactions")

# Step 7: Create Sales column
print("\n6. Creating Sales variable (UnitPrice × Quantity)...")
df['Sales'] = df['UnitPrice'] * df['Quantity']
print(f"   ✓ Sales column created")

# Step 8: Clean Description
df['Description'] = df['Description'].astype(str).str.strip().str.upper()

# Step 9: Remove non-product items (MODEL CODINGAN 1)
print("\n7. Removing non-product items...")
non_products = [
    r'\bPOSTAGE\b', r'\bPOST\b', r'\bCARRIAGE\b', r'\bBANK CHARGES\b', r'\bFEE\b',
    r'\bMANUAL\b', r'\bADJUST\b', r'\bDOTCOM\b', r'\bCRUK\b', r'\bDISCOUNT\b',
    r'\bDAMAGED\b', r'\bLOST\b', r'\bFOUND\b', r'\bTHROWN\b', r'\bFAULT\b',
    r'\bWRONG\b', r'\bGIVEN AWAY\b', r'\bTEST\b', r'\bSAMPLE\b', r'\bSAMPLES\b',
    r'\bAMAZON FEE\b', r'\bEBAY FEE\b'
]
pattern = '|'.join(non_products)
df = df[~df['Description'].str.contains(pattern, regex=True, na=False)]
after_products = len(df)
print(f"   Remaining: {after_products:,} transactions")

# Step 10: Remove single-product invoices (MODEL CODINGAN 1)
print("\n8. Dropping transactions with only ONE product...")
print("   (Study focus: products bought TOGETHER)")
items_per_invoice = df.groupby('InvoiceNo')['Description'].nunique()
single_invoice_ids = items_per_invoice[items_per_invoice == 1].index
before_single = len(df)
df = df[~df['InvoiceNo'].isin(single_invoice_ids)]
final = len(df)
print(f"   Single-product transactions removed: {before_single - final:,}")
print(f"   Remaining: {final:,} transactions")

print(f"\n{'='*50}")
print(f"FINAL DATASET: {final:,} transactions")
print(f"Journal expected: 159,940 transactions")
print(f"Difference: {abs(final - 159940):,}")
print(f"{'='*50}")

# ========================================
# B. EXPLORATORY DATA ANALYSIS (EDA)
# ========================================
print("\n" + "="*90)
print("B. EXPLORATORY DATA ANALYSIS (EDA)")
print("="*90)

# Convert InvoiceDate
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['YearMonth'] = df['InvoiceDate'].dt.to_period('M')

# Calculate monthly sales
monthly_sales = df.groupby('YearMonth')['Sales'].sum()

# Statistics
total_invoices = df['InvoiceNo'].nunique()
total_products = df['Description'].nunique()
total_customers = df['CustomerID'].nunique()

print(f"\n📊 Statistics:")
print(f"   Unique Invoices: {total_invoices:,}")
print(f"   Unique Products: {total_products:,}")
print(f"   Unique Customers: {total_customers:,}")

# ========================================
# Fig. 2. Line chart showing total sales by month
# ========================================
print("\n" + "-"*90)
print("Fig. 2. Line chart showing total sales by month")
print("-"*90)
print("\nInsight: Sales spike from November (Christmas gifting season)")

plt.figure(figsize=(12, 6))
sales_millions = monthly_sales / 1e6
plt.plot(range(len(sales_millions)), sales_millions.values,
         marker='o', linewidth=2, markersize=7, color='steelblue')
plt.xlabel('Month', fontsize=11)
plt.ylabel('Total Sales (×1e6)', fontsize=11)
plt.title('Fig. 2. Line chart showing total sales by month', fontsize=12, fontweight='bold')
month_labels = [str(m) for m in monthly_sales.index]
plt.xticks(range(len(month_labels)), month_labels, rotation=45, ha='right')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Distribution of items per transaction
items_per_trans = df.groupby('InvoiceNo').size()
print(f"\nItems per transaction:")
print(f"   Mean: {items_per_trans.mean():.2f}")
print(f"   Median: {items_per_trans.median():.0f}")

plt.figure(figsize=(10, 5))
plt.hist(items_per_trans, bins=50, color='coral', edgecolor='black', alpha=0.7)
plt.xlabel('Number of Items per Transaction', fontsize=11)
plt.ylabel('Frequency', fontsize=11)
plt.title('Distribution of Items per Transaction', fontsize=12, fontweight='bold')
plt.xlim(0, 50)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# ========================================
# C. ASSOCIATION RULE MINING
# ========================================
print("\n" + "="*90)
print("C. ASSOCIATION RULE MINING")
print("="*90)

print("\nKey Concepts:")
print("• Association rule: X → Y (X and Y are product sets)")
print("• Support: Frequency of itemset occurrence")
print("• Confidence: Strength of relationship")
print("• Lift: Measure of association strength")
print("  - Lift > 1: Positive correlation")
print("  - Lift = 1: Independent")
print("  - Lift < 1: Negative correlation")

# ========================================
# D. APRIORI ALGORITHM
# ========================================
print("\n" + "="*90)
print("D. APRIORI ALGORITHM")
print("="*90)

print("\nApriori Algorithm (Agrawal & Srikant, 1994):")
print("• Method: Generate candidate itemsets by extending shorter itemsets")
print("• Uses scan test to identify frequent itemsets")

# ========================================
# Fig. 3. Steps in Apriori Algorithm
# ========================================
print("\n" + "-"*90)
print("Fig. 3. Steps in Apriori Algorithm")
print("-"*90)
print("""
┌─────────────────────────────────┐
│        Dataset                  │
└──────────────┬──────────────────┘
               │
               ▼
┌─────────────────────────────────┐
│  Generate K-itemset candidates  │◄──┐
└──────────────┬──────────────────┘   │
               │                       │
               ▼                       │ No
      ┌────────────────┐              │
      │ Is set of K-   │──────────────┘
      │ frequent NULL? │
      └───────┬────────┘
              │ Yes
              ▼
┌─────────────────────────────────┐
│          Pruning                │
└──────────────┬──────────────────┘
               │
               ▼
┌─────────────────────────────────┐
│      Frequent items             │
└─────────────────────────────────┘
""")

# ========================================
# Prepare Basket Matrix - MODEL CODINGAN 1
# ========================================
print("\n" + "-"*90)
print("Creating Transaction Basket Matrix")
print("-"*90)

print("\n⏳ Processing... (this may take a few minutes)")

# Create basket: sum quantity per invoice-description (MODEL CODINGAN 1)
basket = df.groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack(fill_value=0)

# Binary encoding
basket_binary = (basket > 0).astype(int)

print(f"✓ Matrix created: {basket_binary.shape[0]:,} invoices × {basket_binary.shape[1]:,} products")

# ========================================
# IV. RESULTS
# ========================================
print("\n" + "="*90)
print("IV. RESULTS")
print("="*90)

print("\nApriori Parameters:")
print("• Minimum support: 0.03 (3%)")
print("• Meaning: Itemsets occurring in at least 3% of transactions")

min_support = 0.03

print(f"\n⏳ Running Apriori algorithm (min_support={min_support})...")

# Run Apriori
frequent_itemsets = apriori(basket_binary, min_support=min_support, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values('support', ascending=False).reset_index(drop=True)

print(f"✓ Completed! Found {len(frequent_itemsets):,} frequent itemsets")

# ========================================
# Fig. 4. Top ten frequent itemsets
# ========================================
print("\n" + "="*90)
print("Fig. 4. Top ten frequent itemsets")
print("="*90)

top10 = frequent_itemsets.head(10).copy()
top10['items'] = top10['itemsets'].apply(lambda x: ', '.join(list(x)))

print("\n>>> frequent_itemsets.head(10)")
print(f"     {'support':>10}   itemsets")
print("-" * 90)

for i, row in top10.iterrows():
    print(f"{i+1:>3}  {row['support']:>10.6f}   ({row['items']})")

# Comparison with journal
print("\n" + "-"*90)
print("COMPARISON WITH JOURNAL (Figure 4)")
print("-"*90)

journal_top10 = [
    ("WHITE HANGING HEART T-LIGHT HOLDER", 0.123573),
    ("JUMBO BAG RED RETROSPOT", 0.095641),
    ("REGENCY CAKESTAND 3 TIER", 0.091916),
    ("PARTY BUNTING", 0.088558),
    ("ASSORTED COLOUR BIRD ORNAMENT", 0.085394),
    ("LUNCH BAG RED RETROSPOT", 0.073845),
    ("SET OF 3 CAKE TINS PANTRY DESIGN", 0.065236),
    ("LUNCH BAG BLACK SKULL", 0.065421),
    ("NATURAL SLATE HEART CHALKBOARD", 0.061549),
    ("HEART OF WICKER SMALL", 0.061141)
]

print(f"\n{'#':<4} {'Journal Item':<45} {'J.Supp':<10} {'Your Supp':<10} {'✓':<5}")
print("-" * 75)

for i, (j_item, j_supp) in enumerate(journal_top10, 1):
    if i <= len(top10):
        y_item = top10.iloc[i-1]['items']
        y_supp = top10.iloc[i-1]['support']
        match = "✓" if j_item in y_item else "✗"
        print(f"{i:<4} {j_item[:43]:<45} {j_supp:<10.6f} {y_supp:<10.6f} {match:<5}")

# ========================================
# Fig. 5. Bar Chart
# ========================================
print("\n" + "-"*90)
print("Fig. 5. Top 10 Frequent Itemsets (Bar Chart)")
print("-"*90)

plt.figure(figsize=(12, 7))

items_short = [item[:40] + '...' if len(item) > 40 else item for item in top10['items']]
supports = top10['support'].values

bars = plt.barh(range(len(items_short)), supports, color='skyblue', edgecolor='navy', linewidth=1.2)
plt.yticks(range(len(items_short)), [f"{i+1}. {item}" for i, item in enumerate(items_short)], fontsize=9)
plt.xlabel('Support', fontsize=11, fontweight='bold')
plt.title('Top 10 Frequent Itemsets', fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

for i, (bar, supp) in enumerate(zip(bars, supports)):
    plt.text(supp + 0.003, i, f'{supp:.6f}', va='center', fontsize=9, fontweight='bold')

plt.grid(axis='x', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

# ========================================
# Association Rules
# ========================================
print("\n" + "-"*90)
print("Generating Association Rules")
print("-"*90)

print("\nParameters:")
print("• Minimum confidence: 0.01")
print("• Minimum lift: 1.0 (positive correlation)")

min_conf = 0.01
min_lift = 1.0

print(f"\n⏳ Generating rules...")

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_conf)
rules = rules[rules['lift'] > min_lift]
rules = rules.sort_values('lift', ascending=False).reset_index(drop=True)

print(f"✓ Generated {len(rules):,} association rules")

# ========================================
# Fig. 6. Result of Association Rules
# ========================================
if len(rules) > 0:
    print("\n" + "="*90)
    print("Fig. 6. Result of Association Rules")
    print("="*90)

    top_rules = rules.head(10).copy()
    top_rules['ant_str'] = top_rules['antecedents'].apply(lambda x: ', '.join(list(x)))
    top_rules['con_str'] = top_rules['consequents'].apply(lambda x: ', '.join(list(x)))

    print("\nTop 10 Rules (sorted by Lift):")
    print(f"\n{'#':<3} antecedents → consequents")
    print(f"{'':>3} {'support':>10} {'confidence':>12} {'lift':>12} {'conviction':>12}")
    print("-" * 90)

    for i, row in top_rules.iterrows():
        ant = row['ant_str'][:28] + '...' if len(row['ant_str']) > 30 else row['ant_str']
        con = row['con_str'][:28] + '...' if len(row['con_str']) > 30 else row['con_str']

        print(f"{i+1:<3} ({ant}) → ({con})")
        print(f"{'':>3} {row['support']:>10.6f} {row['confidence']:>12.6f} {row['lift']:>12.6f} {row['conviction']:>12.6f}")
        if i < 9:
            print()

    # Journal findings
    print("\n" + "-"*90)
    print("Key Findings from Journal")
    print("-"*90)

    print("\n1. Highest Lift Rule:")
    print("   ROSES REGENCY TEACUP AND SAUCER → GREEN REGENCY TEACUP AND SAUCER")
    print("   Lift: 17.3981 (highly correlated)")

    print("\n2. Strong Rule:")
    print("   LUNCH BAG PINK POLKADOT → LUNCH BAG RED RETROSPOT")
    print("   Lift: 7.5034 (customers buying one likely buy the other)")

    # Verify if these exist
    print("\n" + "-"*90)
    print("Verification: Searching for Journal's Key Rules")
    print("-"*90)

    rules_str = rules.copy()
    rules_str['ant_str'] = rules_str['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_str['con_str'] = rules_str['consequents'].apply(lambda x: ', '.join(list(x)))

    # TEACUP rules
    teacup = rules_str[
        rules_str['ant_str'].str.contains('REGENCY TEACUP', na=False) |
        rules_str['con_str'].str.contains('REGENCY TEACUP', na=False)
    ]

    if len(teacup) > 0:
        print(f"\n✓ Found {len(teacup)} REGENCY TEACUP rules")
        best = teacup.iloc[0]
        print(f"   Top: {best['ant_str']} → {best['con_str']}")
        print(f"   Lift: {best['lift']:.4f}")

    # LUNCH BAG rules
    lunchbag = rules_str[
        rules_str['ant_str'].str.contains('LUNCH BAG', na=False) &
        rules_str['con_str'].str.contains('LUNCH BAG', na=False)
    ]

    if len(lunchbag) > 0:
        print(f"\n✓ Found {len(lunchbag)} LUNCH BAG combination rules")
        best = lunchbag.iloc[0]
        print(f"   Top: {best['ant_str']} → {best['con_str']}")
        print(f"   Lift: {best['lift']:.4f}")

    # Statistics
    print("\n" + "-"*90)
    print("Rules Statistics")
    print("-"*90)
    print(f"\nSupport    : {rules['support'].min():.6f} - {rules['support'].max():.6f} (mean: {rules['support'].mean():.6f})")
    print(f"Confidence : {rules['confidence'].min():.6f} - {rules['confidence'].max():.6f} (mean: {rules['confidence'].mean():.6f})")
    print(f"Lift       : {rules['lift'].min():.6f} - {rules['lift'].max():.6f} (mean: {rules['lift'].mean():.6f})")

# ========================================
# Export Results - MENAMPILKAN SEMUA HINGGA MIN SUPPORT 0.03
# ========================================
print("\n" + "="*90)
print("EXPORTING RESULTS")
print("="*90)

# Mengambil semua frequent itemsets (sudah terfilter 0.03 di langkah sebelumnya)
freq_exp = frequent_itemsets.copy()

# Mengubah format frozenset menjadi string agar terbaca rapi di Excel
freq_exp['itemsets'] = freq_exp['itemsets'].apply(lambda x: ', '.join(list(x)))

# Export ke CSV (Menyimpan seluruh baris tanpa limit)
freq_exp.to_csv('frequent_itemsets.csv', index=False)

print(f"\n✓ Berhasil mengekspor SEMUA frequent itemsets ke frequent_itemsets.csv")
print(f"✓ Total itemsets yang diekspor (min_support 0.03): {len(freq_exp):,}")

if len(rules) > 0:
    rules_exp = rules.copy()
    rules_exp['antecedents'] = rules_exp['antecedents'].apply(lambda x: ', '.join(list(x)))
    rules_exp['consequents'] = rules_exp['consequents'].apply(lambda x: ', '.join(list(x)))
    rules_exp.to_csv('association_rules.csv', index=False)
    print(f"✓ association_rules.csv ({len(rules_exp):,} rules)")

# ========================================
# SUMMARY
# ========================================
print("\n" + "="*90)
print("SUMMARY")
print("="*90)

print(f"\n📊 Results:")
print(f"   Initial: 541,909 → Final: {final:,} transactions")
print(f"   Frequent itemsets: {len(frequent_itemsets):,}")
if len(rules) > 0:
    print(f"   Association rules: {len(rules):,}")

print("\n💡 Business Insights:")
print("   • Candlelight holders, bags, tableware frequently bought together")
print("   • Product bundling opportunities (e.g., teacup sets)")
print("   • Cross-selling strategies (recommend complementary items)")
print("   • November sales spike (Christmas season planning)")

print("\n" + "="*90)
print("✅ ANALYSIS COMPLETED!")
print("="*90)
print("\n📁 Files: frequent_itemsets.csv, association_rules.csv")
print("📊 All figures from journal reproduced!")
print("="*90)